#!/bin/bash

EXT_ADDR=$1
HOSTNAME=$2

IFACE=$(ls /sys/class/net/ | grep -v 'lo\|tap*\|br*')

echo "Starting setup..."

apt-get update
apt-get -y --with-new-pkgs upgrade
apt-get -y dist-upgrade
apt-get autoremove
apt-get -y install htop tmux sudo iptables iptables-persistent isc-dhcp-server fail2ban

systemctl enable systemd-networkd

sed -i 's/#Port 22/Port 22098/g' /etc/ssh/sshd_config

echo "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd

echo "[NetDev]
Name=br0
Kind=bridge
" >> /etc/systemd/network/br0.netdev

echo "[Match]
Name=br0

[Address]
Address=10.1.0.1/24

[Network]
ConfigureWithoutCarrier=yes
" >> /etc/systemd/network/br0.network

echo "[NetDev]
Name=tap_vpn
Kind=tap
" >> /etc/systemd/network/softether.netdev

echo "[Match]
Name=tap_vpn

[Network]
ConfigureWithoutCarrier=yes
Bridge=br0
" >> /etc/systemd/network/softether.network

echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
echo "INTERFACESv4=\"br0\"" >> /etc/default/isc-dhcp-server

mv /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.def

echo "option domain-name \"${HOSTNAME}\";
option domain-name-servers 8.8.8.8, 8.8.4.4;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;

authoritative;

subnet 10.1.0.0 netmask 255.255.255.0 {
    range 10.1.0.50 10.1.0.254;
    option subnet-mask 255.255.255.0;
    option routers 10.1.0.1;
    option broadcast-address 10.1.0.255;
}" > /etc/dhcp/dhcpd.conf

echo "# Generated by iptables-save v1.8.7 on Thu May 12 17:29:08 2022
*filter
:INPUT DROP [66:3391]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22098 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5555 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p udp -m udp --dport 443 -j ACCEPT
-A INPUT -p udp -m udp --dport 500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j ACCEPT
-A INPUT -p udp -m udp --dport 4500 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i br0 -o ${IFACE} -j ACCEPT
COMMIT
# Completed on Thu May 12 17:29:08 2022
# Generated by iptables-save v1.8.7 on Thu May 12 17:29:08 2022
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o ${IFACE} -j SNAT --to-source ${EXT_ADDR}
COMMIT
# Completed on Thu May 12 17:29:08 2022" > /etc/iptables/rules.v4

#reboot
